version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../../tmp/together:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docdevker-entrypo-intdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: together
      POSTGRES_HOST_AUTH_METHOD: trust
  pg-admin-request:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "8082:80"
    depends_on:
      - db
  together:
    build:
      context: .
      args:
        ENVIRONMENT: 'default'
        SECRET_KEY: 'some key'
    entrypoint: /bin/sh -c "sleep 5 && python3 manage.py migrate  &&  gunicorn -w 2 -b 0.0.0.0:5000 together.wsgi:application --reload"
    volumes:
      - .:/opt
    ports:
      - "8001:5000"
    depends_on:
      - pg-admin-request
    env_file: development.env
    environment:
      DB_HOSTNAME: db
      DB_NAME: together
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
