# Generated by Django 3.1 on 2020-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='type',
            field=models.CharField(choices=[('shelter', 'Albergue'), ('supply_center', 'Centro de acopio')], max_length=50),
        ),
    ]
